# Basic Matrix Operations

### Matrix Addition

Let $A=[a_{ij}]$ and $B=[b_{ij}]$ be two matrices of dimensions $m \times n$. Then the sum of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times n$, where $c_{ij}=a_{ij}+b_{ij}$.

### Matrix Scalar Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and let $k$ be a scalar. Then the product of matrix $A$ and scalar $k$ is the matrix $B=[b_{ij}]$ of dimensions $m \times n$, where $b_{ij}=k \cdot a_{ij}$.

### Matrix Multiplication

Let $A=[a_{ij}]$ be a matrix of dimensions $m \times n$, and $B=[b_{ij}]$ be a matrix of dimensions $n \times p$. Then the product of matrices $A$ and $B$ is the matrix $C=[c_{ij}]$ of dimensions $m \times p$, where $c_{ij}=\sum_{k=1}^{n} a_{ik} \cdot b_{kj}$.


### Example 1

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.
Then the sum of matrices $A$ and $B$ is

$$
C=
A+B=\begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix}=\begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}.
$$

### Example 2

Let $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $k=2$.

Then the product of matrix $A$ and scalar $k$ is

$$
B=
k \cdot A=2 \cdot \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}=\begin{bmatrix} 2*1 & 2*2 \\ 2*3 & 2*4 \end{bmatrix}=\begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}.
$$

### Example 3

Let
$A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
and
$B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

Then the product of matrices $A$ and $B$ is

$$
C=
A \cdot B=\begin{bmatrix} 1*5+2*7 & 1*6+2*8 \\ 3*5+4*7 & 3*6+4*8 \end{bmatrix}=\begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}.
$$

In [1]:
# Example 1: Matrix addition in sympy
import sympy as sp

A=sp.Matrix([[1,2],[3,4]])
B=sp.Matrix([[5,6],[7,8]])
A # display matrix A

Matrix([
[1, 2],
[3, 4]])

In [2]:
B # display matrix B

Matrix([
[5, 6],
[7, 8]])

In [3]:
sp.Matrix([[6,8],[10,12]])==A+B # verify matrix addition

True

In [4]:
# Example 2: Scalar multiplication
A=sp.Matrix([[1,2],[3,4]]) # define matrix A

sp.Matrix([[2,4],[6,8]])==2*A # verify scalar multiplication

True

In [5]:
# Example 3: Multiplication of two matrices

A=sp.Matrix([[1,2],[3,4]]) # define matrix A
B=sp.Matrix([[5,6],[7,8]]) # define matrix B

sp.Matrix([[19,22],[43,50]])==A*B # verify matrix multiplication

True

### Necessary Condition for Matrix Multiplication

Remember that matrices can have different numbers of rows and columns.

To multiply two matrices $A_{m \times n}$ and $B_{n \times k}$, where $A$ has dimensions $m \times n$ and $B$ has dimensions $n \times k$, the number of columns of matrix $A$ must equal the number of rows of matrix $B$. Otherwise, matrix multiplication is not possible.

$$
A_{m \times n} \cdot B_{n \times k} = C_{m \times k}
$$

For example, if $A_{3 \times 3}$ and $B_{3 \times 3}$, then the resulting matrix $C_{3 \times 3}$.

<img src="https://www.mscroggs.co.uk/img/full/multiply_matrices.gif" alt="Matrix Multiplication GIF" width="400">

### Matrix Multiplication is Not Commutative

Matrix multiplication is not commutative, i.e., in general $A \cdot B \neq B \cdot A$.

In [6]:
# Example of multiplying rectangular matrices
import sympy as sp
A=sp.Matrix([[1,2],[3,4],[5,6]]) # define matrix A_{3 x 2}
B=sp.Matrix([[1,2,3],[4,5,6]]) # define matrix B_{2 x 3}
C=sp.Matrix([[9,12,15],[19,26,33],[29,40,51]]) # define matrix C_{3 x 3}

A*B # multiply matrices A and B to get a 3x3 matrix

Matrix([
[ 9, 12, 15],
[19, 26, 33],
[29, 40, 51]])

In [7]:
B*A # multiply matrices B and A to get a 2x2 matrix

Matrix([
[22, 28],
[49, 64]])

In [8]:
B*C # multiply matrices B and C to get a 2x3 matrix

Matrix([
[134, 184, 234],
[305, 418, 531]])

---
## Exercises for Students (old version)

1. Calculate the sum of matrices $A=\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$.

2. Calculate the product of matrix $A=\begin{bmatrix} 4 & 2 \\ 12 & 4 \end{bmatrix}$ and scalar $k=\frac{1}{4}$.

3. Calculate the products $A\cdot B$ and $B \cdot A$ for matrices $A=\begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix}$ and $B=\begin{bmatrix} 4 & 1 \\ 6 & 4 \end{bmatrix}$.


## Exercises for Students (new version)

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1. Calculate: $\mathbf{A}+\mathbf{B}$;  $\mathbf{B}-\mathbf{A}$;  $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2. Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$, and $4\mathbf{D}$.

3. Calculate the products $\mathbf{A}\cdot \mathbf{B}$; $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$; $\mathbf{D} \cdot \mathbf{E}$.

In [12]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# Task 1: Perform the required addition and subtraction operations
result_1 = A + B
result_2 = B - A
result_3 = A + C
result_4 = D[:, :2] + E[:2, :]  # Use the first two columns of D and the first two rows of E

# Task 2: Perform scalar multiplications
result_5 = 0.5 * A
result_6 = 2 * B
result_7 = -3 * C
result_8 = 4 * D

# Task 3: Compute matrix products
product_1 = np.dot(A, B)  # A multiplied by B
product_2 = np.dot(B, A)  # B multiplied by A
product_3 = np.dot(A, D[:, :2])  # A multiplied by the first two columns of D
product_4 = np.dot(D.T, E.T)  # Transpose of D multiplied by the transpose of E

# Print the results
print("A + B =\n", result_1)
print("B - A =\n", result_2)
print("A + C =\n", result_3)
print("D + E[:2, :] =\n", result_4)
print("0.5 * A =\n", result_5)
print("2 * B =\n", result_6)
print("-3 * C =\n", result_7)
print("4 * D =\n", result_8)
print("A · B =\n", product_1)
print("B · A =\n", product_2)
print("A · D =\n", product_3)
print("D · E (using transpose) =\n", product_4)



A + B =
 [[ 6  8]
 [10 12]]
B - A =
 [[4 4]
 [4 4]]
A + C =
 [[0 4]
 [6 4]]
D + E[:2, :] =
 [[0 4]
 [8 5]]
0.5 * A =
 [[0.5 1. ]
 [1.5 2. ]]
2 * B =
 [[10 12]
 [14 16]]
-3 * C =
 [[ 3 -6]
 [-9  0]]
4 * D =
 [[-4  8 12]
 [16  0 24]]
A · B =
 [[19 22]
 [43 50]]
B · A =
 [[23 34]
 [31 46]]
A · D =
 [[ 7  2]
 [13  6]]
D · E (using transpose) =
 [[ 7 16 25]
 [ 2  8 14]
 [15 42 69]]
